/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Song = IDL.Record({
  'id' : IDL.Nat,
  'moods' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'language' : IDL.Text,
  'genre' : IDL.Text,
  'artist' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAvailableMoods' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getSongsByLanguage' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
  'getSongsByMood' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Song = IDL.Record({
    'id' : IDL.Nat,
    'moods' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'language' : IDL.Text,
    'genre' : IDL.Text,
    'artist' : IDL.Text,
  });
  
  return IDL.Service({
    'getAvailableMoods' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getSongsByLanguage' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
    'getSongsByMood' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };